### ISSUE TITLE
FPGA&CPLD:Турборежим

### ISSUE THREAD

**Issue by solegstar** [andykarpov/karabas-pro#13]
Добавить режим повышенного быстродействия Профи.

**Comment by andykarpov** [comment]
Тут надо думать, как подружить турбо-режим, память и самое главное - проброс zx bus в CPLD

**Comment by andykarpov** [comment]
У нас шина для проброса сигналов ZX BUS имеет разрядность 8 бит.
И пробрасывается из FPGA в CPLD она за 4 такта клока 28 МГц.
Соответственно, в турбо режиме нужно будет умножить тактовую проброса на 2.
То есть, вероятно, весь дизайн перевести на 56 МГц :)
