### ISSUE TITLE
Karabas-pro BIOS

### ISSUE THREAD

**Issue by andykarpov** [andykarpov/karabas-pro#54]
Подумать над ТЗ, что должно входить в концепцию BIOS'а для karabas-pro, разработать прототипы экранов и ТЗ для MVP версии. Продумать, как ПЗУ с BIOS будет стартовать, откуда и как переключаться на выбранную прошивку и конфиг и тп.

**Comment by nihirash** [comment]
Желательно описать еще как сохранять настройки, чтобы после выключения не начинать с чистого листа 😸

Часы, как я понимаю, не то, чтобы свободны

**Comment by andykarpov** [comment]
Пока потребность BIOS'а частично закрыли новым OSD.
Как будут сформированы новые идеи - переоткроем.
