### ISSUE TITLE
Add +5V supply voltage to pin 9 of the VGA connector through footprint 0805.

### ISSUE THREAD

**Issue by solegstar** [andykarpov/karabas-pro#7]
Add + 5V supply voltage to pin 9 of the VGA connector through footprint 0805.

Several purposes are possible:
1. For normal use of the VGA connector - do not solder anything.
2. When using a VGA-HDMI converter, or if you need power at the VGA connector, solder a 0 Ohm resistor.
3. When using the VGA-SCART cable, you can solder a 150-200 ohm resistor and use it to switch the TV to the RGB mode.

**Comment by andykarpov** [comment]
Done
